#!/bin/bash
export MSYS_NO_PATHCONV=1

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Usage: $0 [command] [options]

  Commands:

  build - Build the docker images for the project.
          You need to do this first.

  start - Starts the 4 indy-node containers and a webserver to allow browsing the ledger.

  cli - Start client container in the indy-cli

  bash - Start client container in a bash shell in /home/indy. The python folder is in /home/indy.

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.

  rebuild - Force a full rebuild of the docker images (no cache)

  rm - Remove project containers and associated volumes.
EOF
exit 1
}

case "$1" in
  start)
      docker-compose up webserver node1 node2 node3 node4
    ;;
  cli)
      docker-compose run --rm -e MODE=client client
    ;;
  bash)
      docker-compose run --rm -e MODE=bash client
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker-compose build
    ;;
  rebuild)
      docker-compose build --no-cache
    ;;
  rm)
      docker-compose down -v --rm all
    ;;
  *)
      usage;;
esac
